version: '2'
services:
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: test
        restart: "always"
        container_name: "panopticon_mongo"
        volumes:
            - ./entrypoint/:/docker-entrypoint-initdb.d/
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: test
            ME_CONFIG_MONGODB_SERVER: panopticon_mongo
        container_name: "panopticon_mongo_admin"