version: '2'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile-develop
        ports:
            - "9000:80"
        container_name: "panopticon_backend"
        volumes:
            - ./app:/app